USE ospc;

DROP PROCEDURE IF EXISTS AddBeatmapPlaycount;
DROP PROCEDURE IF EXISTS AddBeatmap;
DROP PROCEDURE IF EXISTS AddBeatmapSet;
DROP PROCEDURE IF EXISTS GetBeatmapById;
DROP PROCEDURE IF EXISTS GetBeatmapSetById;
DROP PROCEDURE IF EXISTS GetPlaycountForBeatmap;
DROP PROCEDURE IF EXISTS GetBeatmapPlaycountForUser;
DROP PROCEDURE IF EXISTS UpdateReferencedBeatmapIdForChannel;
DROP PROCEDURE IF EXISTS GetReferencedBeatmapIdForChannel;
DROP PROCEDURE IF EXISTS AddDiscordPlayerMapping;
DROP PROCEDURE IF EXISTS GetPlayerInfoFromDiscordId;
DROP PROCEDURE IF EXISTS AddUser;
DROP PROCEDURE IF EXISTS GetUserById;
DROP PROCEDURE IF EXISTS GetUserByUsername;
DROP PROCEDURE IF EXISTS GetUserByDiscordId;
